name: Build and Push  Images

on:
  push:
    branches:
      - openvscode-server
  workflow_dispatch:

env:
  REGISTRY_PREFIX: terencelau
  VSCODE_VERSION: openvscode-server-v1.102.3
  TARGETPLATFORM: linux/amd64
  VSCODE_VERSION: openvscode-server-v1.102.3
  PROJECT_NAME: openvscode-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY_PREFIX: ${{ env.REGISTRY_PREFIX }}
      VSCODE_VERSION: ${{ env.VSCODE_VERSION }}
      TARGETPLATFORM: ${{ env.TARGETPLATFORM }}
      BASE_IMAGE_NAME: ${{ env.REGISTRY_PREFIX }}/openvscode-server
      PYTHON_IMAGE_NAME: ${{ env.REGISTRY_PREFIX }}/openvscode-server
      BASE_IMAGE_TAG: ${{ env.VSCODE_VERSION }}-base
      PYTHON_IMAGE_TAG: ${{ env.VSCODE_VERSION }}-python

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU (for multi-platform build)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build base image
      run: |
        docker build \
          -f openvscode-server/base/Dockerfile \
          -t $BASE_IMAGE_NAME:$BASE_IMAGE_TAG \
          --build-arg TARGETPLATFORM=$TARGETPLATFORM \
          --build-arg VSCODE_VERSION=$VSCODE_VERSION \
          openvscode-server/base
        docker tag $BASE_IMAGE_NAME:$BASE_IMAGE_TAG $BASE_IMAGE_NAME:latest-base

    - name: Build python image
      run: |
        docker build \
          -f openvscode-server/python/Dockerfile \
          -t $PYTHON_IMAGE_NAME:$PYTHON_IMAGE_TAG \
          --build-arg TARGETPLATFORM=$TARGETPLATFORM \
          --build-arg REGISTRY_PREFIX=$REGISTRY_PREFIX \
          openvscode-server/python
        docker tag $PYTHON_IMAGE_NAME:$PYTHON_IMAGE_TAG $PYTHON_IMAGE_NAME:latest-python

    - name: Push base image
      run: |
        docker push $BASE_IMAGE_NAME:$BASE_IMAGE_TAG
        docker push $BASE_IMAGE_NAME:latest-base

    - name: Push python image
      run: |
        docker push $PYTHON_IMAGE_NAME:$PYTHON_IMAGE_TAG
        docker push $PYTHON_IMAGE_NAME:latest-python
