name: Build and Push Images 

on:
  push:
    branches:
      - code-server
  workflow_dispatch:

env:
  REGISTRY_PREFIX: terencelau
  TARGETPLATFORM: linux/amd64
  IMAGE_NAME: terencelau/code-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set dynamic image tag
      run: |
        echo "BASE_IMAGE_TAG=code-server-base" >> $GITHUB_ENV

    - name: Build base image
      run: |
        docker build \
          -f code-server/base/Dockerfile \
          -t $IMAGE_NAME:$BASE_IMAGE_TAG \
          code-server/base

    - name: Push base image
      run: |
        docker push $IMAGE_NAME:$BASE_IMAGE_TAG