name: Build and Push Images

on:
  push:
    branches:
      - kubeflow
  workflow_dispatch:

env:
  REGISTRY_PREFIX: terencelau
  TARGETPLATFORM: linux/amd64
  PROJECT_NAME: kubeflow
  BASE_IMAGE: ubuntu
  BASE_IMAGE_VERSION: 24.04
  IMAGE_NAME: terencelau/kubeflow
  JUPYTER_VERSION: 7.3.2
  JUPYTERLAB_VERSION: 4.3.5
  NODE_MAJOR_VERSION: 20
  MINIFORGE_VERSION: 25.3.1-0
  PIP_VERSION: 24.3.1
  PYTHON_VERSION: 3.11.11
  CUDA_VERSION: 12.4
  PYTORCH_VERSION: 2.5.1
  TORCHAUDIO_VERSION: 2.5.1
  TORCHVISION_VERSION: 0.20.1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set dynamic image tag
      run: |
        echo "BASE_IMAGE_TAG=${{ env.PROJECT_NAME }}-${{ env.BASE_IMAGE }}-${{ env.BASE_IMAGE_VERSION }}" >> $GITHUB_ENV
        echo "JUPYTER_BASE_IMAGE_TAG=${{ env.PROJECT_NAME }}-${{ env.BASE_IMAGE }}-${{ env.BASE_IMAGE_VERSION }}-jupyter-${{ env.JUPYTER_VERSION }}" >> $GITHUB_ENV
        echo "JUPYTER_CUDA_PYTORCH_IMAGE_TAG=${{ env.PROJECT_NAME }}-${{ env.BASE_IMAGE }}-${{ env.BASE_IMAGE_VERSION }}-jupyter-${{ env.JUPYTER_VERSION }}-cuda-${{ env.CUDA_VERSION }}-pytorch-${{ env.PYTORCH_VERSION }}" >> $GITHUB_ENV
        echo "CODESERVER_IMAGE_TAG=${{ env.PROJECT_NAME }}-${{ env.BASE_IMAGE }}-${{ env.BASE_IMAGE_VERSION }}-code-server-${{ env.CODESERVER_VERSION }}" >> $GITHUB_ENV
        
    ### base image    
    - name: Build base image
      run: |
        docker build \
          -f kubeflow/base/Dockerfile \
          -t $IMAGE_NAME:$BASE_IMAGE_TAG \
          --build-arg BASE_IMAGE=$BASE_IMAGE \
          --build-arg BASE_IMAGE_VERSION=$BASE_IMAGE_VERSION \
          --build-arg MINIFORGE_VERSION=$MINIFORGE_VERSION \
          --build-arg PIP_VERSION=$PIP_VERSION \
          --build-arg PYTHON_VERSION=$PYTHON_VERSION \
          kubeflow/base
        docker tag $IMAGE_NAME:$BASE_IMAGE_TAG $IMAGE_NAME:latest-base

    - name: Push base image
      run: |
        docker push $IMAGE_NAME:$BASE_IMAGE_TAG
        docker push $IMAGE_NAME:latest-base

    - name: Build jupyter-base image
      run: |
        docker build \
          -f kubeflow/jupyter/Dockerfile \
          -t $IMAGE_NAME:$JUPYTER_BASE_IMAGE_TAG \
          --build-arg BASE_IMAGE_TAG=$BASE_IMAGE_TAG \
          --build-arg PROJECT_NAME=$PROJECT_NAME \
          --build-arg REGISTRY_PREFIX=$REGISTRY_PREFIX \
          --build-arg JUPYTER_VERSION=$JUPYTER_VERSION \
          --build-arg JUPYTERLAB_VERSION=$JUPYTERLAB_VERSION \
          --build-arg MINIFORGE_VERSION=$MINIFORGE_VERSION \
          --build-arg NODE_MAJOR_VERSION=$NODE_MAJOR_VERSION \
          --build-arg PIP_VERSION=$PIP_VERSION \
          --build-arg PYTHON_VERSION=$PYTHON_VERSION \
          kubeflow/jupyter
        docker tag $IMAGE_NAME:$JUPYTER_BASE_IMAGE_TAG $IMAGE_NAME:latest-jupyter-base

    - name: Push jupyter-base image
      run: |
        docker push $IMAGE_NAME:$JUPYTER_BASE_IMAGE_TAG
        docker push $IMAGE_NAME:latest-jupyter-base

    - name: Build jupyter-cuda-pytorch image
      run: |
        docker build \
          -f kubeflow/jupyter-cuda-torch/Dockerfile \
          -t $IMAGE_NAME:$JUPYTER_CUDA_PYTORCH_IMAGE_TAG \
          --build-arg BASE_IMAGE_TAG=$JUPYTER_BASE_IMAGE_TAG \
          --build-arg PROJECT_NAME=$PROJECT_NAME \
          --build-arg REGISTRY_PREFIX=$REGISTRY_PREFIX \
          --build-arg CUDA_VERSION=$CUDA_VERSION \
          --build-arg PYTORCH_VERSION=$PYTORCH_VERSION \
          --build-arg TORCHAUDIO_VERSION=$TORCHAUDIO_VERSION \
          --build-arg TORCHVISION_VERSION=$TORCHVISION_VERSION \
          kubeflow/jupyter-cuda-torch
        docker tag $IMAGE_NAME:$JUPYTER_CUDA_PYTORCH_IMAGE_TAG $IMAGE_NAME:latest-jupyter-cuda-pytorch

    - name: Push jupyter-cuda-pytorch image
      run: |
        docker push $IMAGE_NAME:$JUPYTER_CUDA_PYTORCH_IMAGE_TAG
        docker push $IMAGE_NAME:latest-jupyter-cuda-pytorch
    
    - name: Build code-server image
      run: |
        docker build \
          -f kubeflow/code-server/Dockerfile \
          -t $IMAGE_NAME:$PROJECT_NAME-code-server-$CODESERVER_VERSION \
          --build-arg BASE_IMAGE_TAG=$BASE_IMAGE_TAG \
          --build-arg PROJECT_NAME=$PROJECT_NAME \
          --build-arg REGISTRY_PREFIX=$REGISTRY_PREFIX \
          --build-arg CUDA_VERSION=$CUDA_VERSION \
          --build-arg PYTORCH_VERSION=$PYTORCH_VERSION \
          --build-arg TORCHAUDIO_VERSION=$TORCHAUDIO_VERSION \
          --build-arg TORCHVISION_VERSION=$TORCHVISION_VERSION \
          --build-arg CODESERVER_VERSION=$CODESERVER_VERSION \
          kubeflow/code-server
        docker tag $IMAGE_NAME:$PROJECT_NAME-code-server-$CODESERVER_VERSION $IMAGE_NAME:latest-code-server

    - name: Push code-server image
      run: |
        docker push $IMAGE_NAME:$PROJECT_NAME-code-server-$CODESERVER_VERSION
        docker push $IMAGE_NAME:latest-code-server